# Classification

### import required packages

In [1]:
import numpy as mp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### load the data

In [2]:
df = pd.read_csv('./framingham.csv')

In [3]:
df

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   
4238     1   40        3.0              0         0.0     0.0   
4239     0   39        3.0              1        30.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   
4238                0             1         0    185.0  141.0   98.0  25.60   
4239                0             0         0    196.0  133.0   86.0  20.91   

      heartRate  glucose  TenYearCHD  
0          80.0     77.0           0  
1          95.0     76.0           0  
2          75.0     70.0           0  
3          65.0    103.0           1  
4          85.0     85.0           0  
...         ...      ...         ...  
4235       84.0     86.0           0  
4236       86.0      NaN           0  
4237       80.0    107.0           0  
4238       67.0     72.0           0  
4239       85.0     80.0           0  

[4240 rows x 16 columns]

### EDA

In [4]:
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [5]:
df.isna().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [6]:
df.shape

(4240, 16)

In [7]:
df1 = df.drop('education', axis = 1 )


In [8]:
df1

male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0        1   39              0         0.0     0.0                0   
1        0   46              0         0.0     0.0                0   
2        1   48              1        20.0     0.0                0   
3        0   61              1        30.0     0.0                0   
4        0   46              1        23.0     0.0                0   
...    ...  ...            ...         ...     ...              ...   
4235     0   48              1        20.0     NaN                0   
4236     0   44              1        15.0     0.0                0   
4237     0   52              0         0.0     0.0                0   
4238     1   40              0         0.0     0.0                0   
4239     0   39              1        30.0     0.0                0   

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  \
0                0         0    195.0  106.0   70.0  26.97       80.0   
1                0         0    250.0  121.0   81.0  28.73       95.0   
2                0         0    245.0  127.5   80.0  25.34       75.0   
3                1         0    225.0  150.0   95.0  28.58       65.0   
4                0         0    285.0  130.0   84.0  23.10       85.0   
...            ...       ...      ...    ...    ...    ...        ...   
4235             0         0    248.0  131.0   72.0  22.00       84.0   
4236             0         0    210.0  126.5   87.0  19.16       86.0   
4237             0         0    269.0  133.5   83.0  21.47       80.0   
4238             1         0    185.0  141.0   98.0  25.60       67.0   
4239             0         0    196.0  133.0   86.0  20.91       85.0   

      glucose  TenYearCHD  
0        77.0           0  
1        76.0           0  
2        70.0           0  
3       103.0           1  
4        85.0           0  
...       ...         ...  
4235     86.0           0  
4236      NaN           0  
4237    107.0           0  
4238     72.0           0  
4239     80.0           0  

[4240 rows x 15 columns]

In [9]:
df1.corr()

male       age  currentSmoker  cigsPerDay    BPMeds  \
male             1.000000 -0.029014       0.197026    0.317143 -0.052504   
age             -0.029014  1.000000      -0.213662   -0.192959  0.123052   
currentSmoker    0.197026 -0.213662       1.000000    0.769774 -0.048927   
cigsPerDay       0.317143 -0.192959       0.769774    1.000000 -0.046155   
BPMeds          -0.052504  0.123052      -0.048927   -0.046155  1.000000   
prevalentStroke -0.004550  0.057679      -0.032980   -0.032711  0.117370   
prevalentHyp     0.005853  0.306799      -0.103710   -0.066645  0.261067   
diabetes         0.015693  0.101314      -0.044285   -0.037089  0.052060   
totChol         -0.070413  0.262554      -0.046488   -0.026479  0.080623   
sysBP           -0.035879  0.394053      -0.130281   -0.088797  0.254194   
diaBP            0.058199  0.205586      -0.107933   -0.056715  0.194122   
BMI              0.081871  0.136096      -0.167857   -0.093293  0.100702   
heartRate       -0.116932 -0.012843       0.062686    0.075564  0.015230   
glucose          0.005979  0.122356      -0.056726   -0.058886  0.051197   
TenYearCHD       0.088374  0.225408       0.019448    0.057755  0.087519   

                 prevalentStroke  prevalentHyp  diabetes   totChol     sysBP  \
male                   -0.004550      0.005853  0.015693 -0.070413 -0.035879   
age                     0.057679      0.306799  0.101314  0.262554  0.394053   
currentSmoker          -0.032980     -0.103710 -0.044285 -0.046488 -0.130281   
cigsPerDay             -0.032711     -0.066645 -0.037089 -0.026479 -0.088797   
BPMeds                  0.117370      0.261067  0.052060  0.080623  0.254194   
prevalentStroke         1.000000      0.074791  0.006955  0.000105  0.057000   
prevalentHyp            0.074791      1.000000  0.077752  0.163632  0.696656   
diabetes                0.006955      0.077752  1.000000  0.040348  0.111265   
totChol                 0.000105      0.163632  0.040348  1.000000  0.208734   
sysBP                   0.057000      0.696656  0.111265  0.208734  1.000000   
diaBP                   0.045153      0.615840  0.050260  0.164698  0.783952   
BMI                     0.025909      0.301344  0.087068  0.115992  0.326906   
heartRate              -0.017674      0.146815  0.048986  0.091127  0.182155   
glucose                 0.018440      0.086656  0.617630  0.046538  0.140573   
TenYearCHD              0.061823      0.177458  0.097344  0.082369  0.216374   

                    diaBP       BMI  heartRate   glucose  TenYearCHD  
male             0.058199  0.081871  -0.116932  0.005979    0.088374  
age              0.205586  0.136096  -0.012843  0.122356    0.225408  
currentSmoker   -0.107933 -0.167857   0.062686 -0.056726    0.019448  
cigsPerDay      -0.056715 -0.093293   0.075564 -0.058886    0.057755  
BPMeds           0.194122  0.100702   0.015230  0.051197    0.087519  
prevalentStroke  0.045153  0.025909  -0.017674  0.018440    0.061823  
prevalentHyp     0.615840  0.301344   0.146815  0.086656    0.177458  
diabetes         0.050260  0.087068   0.048986  0.617630    0.097344  
totChol          0.164698  0.115992   0.091127  0.046538    0.082369  
sysBP            0.783952  0.326906   0.182155  0.140573    0.216374  
diaBP            1.000000  0.377360   0.181021  0.061075    0.145112  
BMI              0.377360  1.000000   0.067451  0.087389    0.075300  
heartRate        0.181021  0.067451   1.000000  0.094546    0.022907  
glucose          0.061075  0.087389   0.094546  1.000000    0.125590  
TenYearCHD       0.145112  0.075300   0.022907  0.125590    1.000000

In [10]:
df_cleaned = df1.dropna()

In [11]:
df_cleaned.isna().sum()

male               0
age                0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

### split the data into x and y

In [12]:
x = df_cleaned[['male', 'cigsPerDay' , 'BPMeds', 'prevalentStroke' , 'prevalentHyp' ,
'diabetes' ,'totChol' ,'sysBP']]

y =df_cleaned['TenYearCHD']

### split the data into train and test sets

In [13]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=12345)

### LogisticRegression Model training

In [14]:
from sklearn.linear_model import LogisticRegressionCV

model_lg = LogisticRegressionCV(max_iter=1000)
model_lg.fit(x_train, y_train)

LogisticRegressionCV(max_iter=1000)

## naive bayes model training 

In [15]:
from sklearn.naive_bayes import GaussianNB

model_nb = GaussianNB()

model_nb.fit(x_train, y_train)

GaussianNB()

### KNN Modeltraining

In [16]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors=7)
model_knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=7)

### SVM Model training

In [17]:
from sklearn.svm import SVC

model_svc = SVC(C=8.0)
model_svc.fit(x_train, y_train)

SVC(C=8.0)

### model evaluation

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(model, model_name):
    # get the predictions
    y_pred = model.predict(x_test)

    # ground truth
    y_true = y_test
    
    print(f"---- {model_name} evaluation ----")
    
    # get the confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    print(f"confusion matrix: ")
    print(cm)

    # get the accuracy score
    print(f"accuracy : {accuracy_score(y_true, y_pred) * 100:.2f}%")

    # get the precision
    print(f"precision: {precision_score(y_true, y_pred):.2f}")

    # get the recall
    print(f"recall: {recall_score(y_true, y_pred):.2f}")

    # get the f1 score
    print(f"F1 Score: {f1_score(y_true, y_pred):.2f}")

In [19]:
evaluate_model(model_lg, 'Logistic Regression')

---- Logistic Regression evaluation ----
confusion matrix: 
[[796   0]
 [139   3]]
accuracy : 85.18%
precision: 1.00
recall: 0.02
F1 Score: 0.04


In [20]:
evaluate_model(model_nb, 'Naive Bayes')

---- Naive Bayes evaluation ----
confusion matrix: 
[[747  49]
 [122  20]]
accuracy : 81.77%
precision: 0.29
recall: 0.14
F1 Score: 0.19


In [21]:
evaluate_model(model_knn, 'KNN')

---- KNN evaluation ----
confusion matrix: 
[[767  29]
 [135   7]]
accuracy : 82.52%
precision: 0.19
recall: 0.05
F1 Score: 0.08


In [22]:
evaluate_model(model_svc, 'SVM')

---- SVM evaluation ----
confusion matrix: 
[[796   0]
 [142   0]]
accuracy : 84.86%
precision: 0.00
recall: 0.00
F1 Score: 0.00


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
