# classification 

Que.3 -

Prepare a model for glass classification using KNN, SVM and Naive Bayes.
Also calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score.
Data Description:
RI : refractive index
Na: Sodium (unit measurement: weight percent in corresponding oxide, as are attributes 4-10)
Mg: Magnesium
AI: Aluminum
Si: Silicon
K:Potassium
Ca: Calcium
Ba: Barium
Fe: Iron
Type: Type of glass: (class attribute)
1 -- building_windows_float_processed
 2 --building_windows_non_float_processed
 3 --vehicle_windows_float_processed
 4 --vehicle_windows_non_float_processed (none in this database)
 5 --containers
 6 --tableware
 7 --headlamps

Dataset : Glass.csv



### import required packages

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### load the data

In [3]:
df = pd.read_csv('./glass.csv')

In [18]:
df.nunique()

RI      178
Na      142
Mg       94
Al      118
Si      133
K        65
Ca      143
Ba       34
Fe       32
Type      6
dtype: int64

In [19]:
df['Type'].unique()

array([1, 2, 3, 5, 6, 7])

### EDA

In [4]:
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [5]:
df.isna().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [6]:
df.corr()

RI        Na        Mg        Al        Si         K        Ca  \
RI    1.000000 -0.191885 -0.122274 -0.407326 -0.542052 -0.289833  0.810403   
Na   -0.191885  1.000000 -0.273732  0.156794 -0.069809 -0.266087 -0.275442   
Mg   -0.122274 -0.273732  1.000000 -0.481799 -0.165927  0.005396 -0.443750   
Al   -0.407326  0.156794 -0.481799  1.000000 -0.005524  0.325958 -0.259592   
Si   -0.542052 -0.069809 -0.165927 -0.005524  1.000000 -0.193331 -0.208732   
K    -0.289833 -0.266087  0.005396  0.325958 -0.193331  1.000000 -0.317836   
Ca    0.810403 -0.275442 -0.443750 -0.259592 -0.208732 -0.317836  1.000000   
Ba   -0.000386  0.326603 -0.492262  0.479404 -0.102151 -0.042618 -0.112841   
Fe    0.143010 -0.241346  0.083060 -0.074402 -0.094201 -0.007719  0.124968   
Type -0.164237  0.502898 -0.744993  0.598829  0.151565 -0.010054  0.000952   

            Ba        Fe      Type  
RI   -0.000386  0.143010 -0.164237  
Na    0.326603 -0.241346  0.502898  
Mg   -0.492262  0.083060 -0.744993  
Al    0.479404 -0.074402  0.598829  
Si   -0.102151 -0.094201  0.151565  
K    -0.042618 -0.007719 -0.010054  
Ca   -0.112841  0.124968  0.000952  
Ba    1.000000 -0.058692  0.575161  
Fe   -0.058692  1.000000 -0.188278  
Type  0.575161 -0.188278  1.000000

### split the data into x and y

In [11]:
x = df.drop(['RI','Si','K','Ca'], axis=1)
y = df['Type']


### split the data into train and test sets

In [12]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=123456)

### Naive Bayes Model training

In [13]:
from sklearn.naive_bayes import GaussianNB

model_nb = GaussianNB()
model_nb.fit(x_train, y_train)

GaussianNB()

### KNN Modeltraining

In [14]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(x_train, y_train)

KNeighborsClassifier()

### SVM Model training

In [15]:
from sklearn.svm import SVC

model_svc = SVC(C=2.0)
model_svc.fit(x_train, y_train)

SVC(C=2.0)

### model evaluation

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(model, model_name):
    # get the predictions
    y_pred = model.predict(x_test)

    # ground truth
    y_true = y_test
    
    print(f"---- {model_name} evaluation ----")
    
    # get the confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    print(f"confusion matrix: ")
    print(cm)

    # get the accuracy score
    print(f"accuracy : {accuracy_score(y_true, y_pred) * 100:.2f}%")

    # get the precision
    print(f"precision: {precision_score(y_true, y_pred,average='macro'):.2f}")

    # get the recall
    print(f"recall: {recall_score(y_true, y_pred,average='macro'):.2f}")

    # get the f1 score
    print(f"F1 Score: {f1_score(y_true, y_pred,average='macro'):.2f}")

In [21]:
evaluate_model(model_nb, 'Naive Bayes')

---- Naive Bayes evaluation ----
confusion matrix: 
[[13  0  0  0  0  0]
 [ 0 19  0  0  0  0]
 [ 0  0  6  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  9]]
accuracy : 100.00%
precision: 1.00
recall: 1.00
F1 Score: 1.00


In [22]:
evaluate_model(model_knn, 'KNN')

---- KNN evaluation ----
confusion matrix: 
[[13  0  0  0  0  0]
 [ 0 19  0  0  0  0]
 [ 0  1  5  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  1  2  6]]
accuracy : 92.59%
precision: 0.88
recall: 0.92
F1 Score: 0.88


In [23]:
evaluate_model(model_svc , 'SVC')

---- SVC evaluation ----
confusion matrix: 
[[13  0  0  0  0  0]
 [ 0 19  0  0  0  0]
 [ 0  6  0  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  0  0  0  0  2]
 [ 0  0  0  0  0  9]]
accuracy : 85.19%
precision: 0.60
recall: 0.67
F1 Score: 0.63


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
